<?php
$this->headTitle('Profile - Change Password');
?>
<div class="page-header">
	<h1>Profile <small>Change Password</small></h1>
</div>
<div class="row">
	<div class="col-lg-12">
		<div class="panel panel-default">
			<div class="panel-heading text-right">
				<div class="btn-group" role="group" aria-label="...">
					<a 
						href="<?php echo $this->url(array('controller' => 'admin_profile', 'action' => 'edit'), 'default', true);?>"
						class="btn btn-default"
						><i class="fa fa-user"></i> Edit Profile</a>
				</div>
			</div>
			<div class="panel-body">
				<form class="form-horizontal" method="post" action="">
					<fieldset>

						<!-- Form Name -->
						<legend>Change Password</legend>

						<!-- Text input-->
						<div class="form-group">
							<label class="col-md-4 control-label" for="first_name">New Password</label>  
							<div class="col-md-4">
								<input type="text" required="required" placeholder="enter new password" class="form-control input-md" value="" id="new_password" name="new_password">
								<span class="help-block">min 5 max 255 characters</span>  
							</div>
							
							
						</div>

						<!-- Text input-->
						<div class="form-group">
							<label class="col-md-4 control-label" for="last_name">Confirm New Password</label>  
							<div class="col-md-4">
								<input type="text" required="required" placeholder="confirm new password" class="form-control input-md" value="" id="new_password_confirm" name="new_password_confirm">
								<span class="help-block"></span>  
							</div>
							
							
						</div>

						<!-- Button (Double) -->
						<div class="form-group">
							<label class="col-md-4 control-label" for="new_member_cancel"></label>
							<div class="col-md-8 text-right">
								<a href="<?php echo $this->url(array('controller'=>'admin_dashboard', 'action'=>'index'), 'default', true); ?>" id="new_member_cancel" name="edit_profile_cancel" class="btn btn-default">Cancel</a>
								<button type="submit" id="new_member_submit" name="change_password_confirm" class="btn btn-success">Change Password</button>
							</div>
						</div>

					</fieldset>
				</form>

			</div>
		</div>
	</div>
</div>
